#Mini-Project: Inputs+Sonar+needs+Secrets
name: Build java application with SonarQube analysis using secret token
on:
   workflow_dispatch:
     inputs:
       job_name:
         description: 'Enter the job name you want to run'
         required: true
         type: choice
         options:
           - job1-build-java-code
           - job2-code-coverage-report
jobs:
  job1-build-java-code:
    if: ${{ github.event.inputs.job_name == 'job1-build-java-code' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.12
      - name: Build with Maven
        run: mvn clean install
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-app-artifacts 
          path: target/
  job2-code-coverage-report:
    if: ${{ github.event.inputs.job_name == 'job2-code-coverage-report' }}
    #needs: job1-build-java-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.12
      - name: Build with Maven
        run: mvn clean package
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-app-artifacts
          path: target/
      - name: Run SonarQube analysis
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
             -Dsonar.organization=${{ vars.SONAR_ORGANISATION_KEY }} \
             -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
             -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
